"""Downloads the icon set and turns it into a C# lookup.

The icons are Hugeicons, the same free set Master Audio Switcher uses, fetched
through Iconify. They are drawn as strokes on a 24 by 24 grid, which is why the
dock draws them with a Path and a stroke rather than with PathIcon, which fills.

The SVG sources are kept in assets/icons-src so the build needs no network and
so a change to the set is a diff rather than a mystery. Re-run after editing
ICONS below:

    python tools/fetch_icons.py

Licence: Hugeicons free set, MIT. See THIRD-PARTY.md.
"""

from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from svgpath import extent, normalise, scale

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCES = ROOT / "assets" / "icons-src"
GENERATED = ROOT / "src" / "MCD.App" / "Widgets" / "IconLibrary.g.cs"

API = "https://api.iconify.design/hugeicons/{name}.svg"

# name in the program -> icon in the set.
# The first six are what the built-in widgets use; the rest are there so that
# someone can pick something else.
ICONS: dict[str, str] = {
    "Cpu": "cpu",
    "Gpu": "gpu",
    "Memory": "ram-memory",
    "Disk": "hard-drive",
    "Network": "internet",
    "Temperature": "temperature",
    "Brush": "thermometer",
    "Fan": "fan-01",
    "Battery": "battery-medium-01",
    # The battery draws one of four, and Wi-Fi one of four, because a bar is
    # glanced at: the shape has to carry the reading before the figure beside
    # it is read, or the figure is the only thing that ever gets read.
    "BatteryFull": "battery-full",
    "BatteryLow": "battery-empty",
    "BatteryCharging": "battery-charging-01",
    "WifiHigh": "wifi-full-signal",
    "WifiMid": "wifi-medium-signal",
    "WifiLow": "wifi-low-signal",
    "WifiNone": "wifi-no-signal",
    "Power": "power",
    "Computer": "computer",
    "Activity": "activity-01",
    "Pulse": "activity-03",
    "Chart": "chart-01",
    "ChartUp": "chart-up",
    "PieChart": "pie-chart",
    "BarChart": "bar-chart",
    "Speedometer": "dashboard-speed-01",
    "Gauge": "dashboard-speed-02",
    "Clock": "clock-01",
    "Wifi": "wifi-02",
    "Download": "download-01",
    "ArrowUp": "arrow-up-02",
    "Previous": "previous",
    "Play": "play",
    "Pause": "pause",
    "Next": "next",
    "Music": "music-note-01",
    "Spacer": "arrow-horizontal",
    # For pinned programs, when the person prefers a drawn icon over the
    # one extracted from the file.
    "Globe": "globe-02",
    "Terminal": "computer-terminal-01",
    "Game": "game-controller-03",
    "Mail": "mail-01",
    "Chat": "message-01",
    "Code": "source-code",
    "Camera": "camera-01",
    "Document": "file-01",
    "Gear": "settings-02",
    "Calculator": "calculator",
    "Book": "book-02",
    "Picture": "image-01",
    "Pen": "pen-01",
    "Video": "video-01",
    "Home": "home-01",
    "ArrowDown": "arrow-down-02",
    "Folder": "folder-01",
    "Rocket": "rocket-01",
    "Star": "star",
    "Shield": "shield-01",
    "Network2": "neural-network",
    "CpuCharge": "cpu-charge",
    # Wireless devices, drawn by what they are.
    "Mouse": "mouse-22",
    "Headset": "headset",
    "Keyboard": "keyboard",
    "Bluetooth": "bluetooth",
    # The settings window draws from this set too, rather than from the
    # system's glyph font: two icon sets in one program read as two programs.
    "Undo": "undo",
    "Delete": "delete-02",
    "Plus": "plus-sign",
    "Layout": "layout-01",
    "Sliders": "sliders-horizontal",
    "Info": "information-circle",
    "List": "list-view",
    # Keeping the machine awake: a cup with steam rising, and the same cup
    # empty (coffee-04-empty is coffee-04 with its steam taken off, kept in
    # assets/icons-src so the build still needs no network).
    "CoffeeOn": "coffee-04",
    "CoffeeOff": "coffee-04-empty",
    "Mic": "mic-01",
    "MicOff": "mic-off-01",
    # The programs Windows brings, for the gallery's "Programs" shelf.
    "Notepad": "note-02",
    "Paint": "paint-board",
    "Scissors": "scissor",
    "StickyNote": "sticky-note-01",
    # The sound widget draws one of four, by how loud it is.
    "Speaker": "volume-high",
    "SpeakerMid": "volume-up",
    "SpeakerLow": "volume-low",
    "SpeakerOff": "volume-mute-01",
    # Chosen on the control panel (tools/panel), from the whole free set.
    "AArrowUp": "a-arrow-up",
    "ALargeSmall": "a-large-small",
    "Acceleration": "acceleration",
    "Accessibility": "accessibility",
    "Accident": "accident",
    "AccountSetting03": "account-setting-03",
    "Activity02": "activity-02",
    "Activity04": "activity-04",
    "ActivityCircle": "activity-circle",
    "AddToList": "add-to-list",
    "AdobeAfterEffect": "adobe-after-effect",
    "AdobeIllustrator": "adobe-illustrator",
    "AdobeIndesign": "adobe-indesign",
    "AdobePhotoshop": "adobe-photoshop",
    "AdobePremier": "adobe-premier",
    "AdobeXd": "adobe-xd",
    "Adventure": "adventure",
    "Advertisiment": "advertisiment",
    "Affiliate": "affiliate",
    "AiBeautify": "ai-beautify",
    "AiBook": "ai-book",
    "AiBrain01": "ai-brain-01",
    "AiBrain03": "ai-brain-03",
    "AiGame": "ai-game",
    "AiProgramming": "ai-programming",
    "AiScan": "ai-scan",
    "Aids": "aids",
    "Airbnb": "airbnb",
    "AircraftGame": "aircraft-game",
    "Airplane01": "airplane-01",
    "Airplane02": "airplane-02",
    "AirplaneLanding01": "airplane-landing-01",
    "AirplaneLanding02": "airplane-landing-02",
    "AirplaneMode": "airplane-mode",
    "AirplaneSeat": "airplane-seat",
    "AirplaneSeat02": "airplane-seat-02",
    "AirplaneTakeOff01": "airplane-take-off-01",
    "AirplaneTakeOff02": "airplane-take-off-02",
    "Airplay": "airplay",
    "AirplayLine": "airplay-line",
    "Airpod01": "airpod-01",
    "Airpod02": "airpod-02",
    "Airpod03": "airpod-03",
    "Airport": "airport",
    "Airport02": "airport-02",
    "AirportTower": "airport-tower",
    "AlarmClock": "alarm-clock",
    "Alien01": "alien-01",
    "Alien02": "alien-02",
    "AlphabetGreek": "alphabet-greek",
    "Amazon": "amazon",
    "Ambulance": "ambulance",
    "AmericanFootball": "american-football",
    "Amie": "amie",
    "Ammo": "ammo",
    "Amphora": "amphora",
    "Ampoule": "ampoule",
    "Anchor": "anchor",
    "Android": "android",
    "Angel": "angel",
    "Angry": "angry",
    "AngryBird": "angry-bird",
    "Annoyed": "annoyed",
    "Anonymous": "anonymous",
    "Api": "api",
    "ApiGateway": "api-gateway",
    "AppStore": "app-store",
    "Apple": "apple",
    "Apple01": "apple-01",
    "AppleFinder": "apple-finder",
    "AppleMusic": "apple-music",
    "AppleNews": "apple-news",
    "ApplePie": "apple-pie",
    "AppleReminder": "apple-reminder",
    "AppleStocks": "apple-stocks",
    "AppleVisionPro": "apple-vision-pro",
    "Apricot": "apricot",
    "Apron": "apron",
    "ArcBrowser": "arc-browser",
    "Archer": "archer",
    "Archive02": "archive-02",
    "Archive03": "archive-03",
    "Archive04": "archive-04",
    "Armchair": "armchair",
    "ArmoredBoot": "armored-boot",
    "ArtificialIntelligence06": "artificial-intelligence-06",
    "Assignments": "assignments",
    "Asterisk": "asterisk",
    "Asterisk02": "asterisk-02",
    "Asteroid01": "asteroid-01",
    "Asteroid02": "asteroid-02",
    "Astronaut01": "astronaut-01",
    "Astronaut02": "astronaut-02",
    "Atom01": "atom-01",
    "Atom02": "atom-02",
    "Attachment01": "attachment-01",
    "Attachment02": "attachment-02",
    "AutomotiveBattery01": "automotive-battery-01",
    "AutomotiveBattery02": "automotive-battery-02",
    "Avocado": "avocado",
    "AwsLambda": "aws-lambda",
    "Baby01": "baby-01",
    "Baby02": "baby-02",
    "BabyBottle": "baby-bottle",
    "BackMuscleBody": "back-muscle-body",
    "Background": "background",
    "Bacteria": "bacteria",
    "BadgeCent": "badge-cent",
    "BadgeDollarSign": "badge-dollar-sign",
    "BadgeEuro": "badge-euro",
    "BadgeIndianRupee": "badge-indian-rupee",
    "BadgeJapaneseYen": "badge-japanese-yen",
    "BadgePoundSterling": "badge-pound-sterling",
    "BadgeRussianRuble": "badge-russian-ruble",
    "BadgeSwissFranc": "badge-swiss-franc",
    "BadgeTurkishLira": "badge-turkish-lira",
    "Badminton": "badminton",
    "BadmintonShuttle": "badminton-shuttle",
    "BalanceScale": "balance-scale",
    "Balloon": "balloon",
    "Balloons": "balloons",
    "Ban": "ban",
    "Banana": "banana",
    "Bandage": "bandage",
    "Bank": "bank",
    "Banknote": "banknote",
    "Barrel": "barrel",
    "Baseball": "baseball",
    "BaseballBat": "baseball-bat",
    "BaseballHelmet": "baseball-helmet",
    "Bash": "bash",
    "Basketball01": "basketball-01",
    "Basketball02": "basketball-02",
    "BasketballHoop": "basketball-hoop",
    "BatteryCharging02": "battery-charging-02",
    "BatteryLowAlt": "battery-low",
    "BatteryMedium02": "battery-medium-02",
    "BbqGrill": "bbq-grill",
    "Beach02": "beach-02",
    "Bean": "bean",
    "BeanOff": "bean-off",
    "Beater": "beater",
    "Bebo": "bebo",
    "Beef": "beef",
    "BeefOff": "beef-off",
    "Beer": "beer",
    "BeerOff": "beer-off",
    "Behance01": "behance-01",
    "Behance02": "behance-02",
    "BicepsFlexed": "biceps-flexed",
    "Bicycle": "bicycle",
    "Bicycle01": "bicycle-01",
    "Bike": "bike",
    "Billiard01": "billiard-01",
    "Billiard02": "billiard-02",
    "Binary": "binary",
    "BinaryCode": "binary-code",
    "Bing": "bing",
    "Biohazard": "biohazard",
    "Bird": "bird",
    "BirthdayCake": "birthday-cake",
    "Biscuit": "biscuit",
    "Bitcoin01": "bitcoin-01",
    "BitcoinLock": "bitcoin-lock",
    "BitcoinMind": "bitcoin-mind",
    "BlackHole": "black-hole",
    "BlackHole01": "black-hole-01",
    "Blender": "blender",
    "BlockGame": "block-game",
    "Blogger": "blogger",
    "Blood": "blood",
    "BloodBag": "blood-bag",
    "BloodBottle": "blood-bottle",
    "BloodPressure": "blood-pressure",
    "BloodType": "blood-type",
    "Blueprint": "blueprint",
    "Bluesky": "bluesky",
    "BluetoothCircle": "bluetooth-circle",
    "BluetoothSearching": "bluetooth-searching",
    "Blur": "blur",
    "BlushBrush01": "blush-brush-01",
    "BlushBrush02": "blush-brush-02",
    "Boat": "boat",
    "BodyArmor": "body-armor",
    "BodyPartLeg": "body-part-leg",
    "BodyPartMuscle": "body-part-muscle",
    "BodyPartSixPack": "body-part-six-pack",
    "BodySoap": "body-soap",
    "BodyWeight": "body-weight",
    "Bold": "bold",
    "Bolt": "bolt",
    "Bomb": "bomb",
    "Bone01": "bone-01",
    "Bone02": "bone-02",
    "BookDown": "book-down",
    "BookHeadphones": "book-headphones",
    "BookMarked": "book-marked",
    "BookMinus": "book-minus",
    "BookOpen02": "book-open-02",
    "BookText": "book-text",
    "Bootstrap": "bootstrap",
    "Bot": "bot",
    "BotMessageSquare": "bot-message-square",
    "BoundingBox": "bounding-box",
    "BowArrow": "bow-arrow",
    "Bowling": "bowling",
    "BowlingBall": "bowling-ball",
    "BowlingPins": "bowling-pins",
    "Boxer": "boxer",
    "BoxingBag": "boxing-bag",
    "BoxingGlove": "boxing-glove",
    "BoxingGlove01": "boxing-glove-01",
    "Brain01": "brain-01",
    "Brain02": "brain-02",
    "Brain03": "brain-03",
    "Brandfetch": "brandfetch",
    "Bread01": "bread-01",
    "Bread02": "bread-02",
    "Bread03": "bread-03",
    "Bread04": "bread-04",
    "Briefcase01": "briefcase-01",
    "Briefcase02": "briefcase-02",
    "Briefcase05": "briefcase-05",
    "Briefcase06": "briefcase-06",
    "Briefcase07": "briefcase-07",
    "Briefcase09": "briefcase-09",
    "BriefcaseBusiness": "briefcase-business",
    "BriefcaseDollar": "briefcase-dollar",
    "BriefcaseMedical": "briefcase-medical",
    "Broccoli": "broccoli",
    "BrokenBone": "broken-bone",
    "BrushAlt": "brush",
    "BrushCleaning": "brush-cleaning",
    "BubbleTea01": "bubble-tea-01",
    "BubbleTea02": "bubble-tea-02",
    "Bucket": "bucket",
    "Bug01": "bug-01",
    "Bug02": "bug-02",
    "Bullet": "bullet",
    "BulletproofVest": "bulletproof-vest",
    "BurjAlArab": "burj-al-arab",
    "Bus01": "bus-01",
    "Bus02": "bus-02",
    "Bus03": "bus-03",
    "BusFront": "bus-front",
    "Cable": "cable",
    "CableCar": "cable-car",
    "Caduceus": "caduceus",
    "Cake": "cake",
    "CakeSlice": "cake-slice",
    "Calculate": "calculate",
    "Calculator01": "calculator-01",
    "Calendar04": "calendar-04",
    "Calendar05": "calendar-05",
    "CalendarDays": "calendar-days",
    "CalendarRange": "calendar-range",
    "Camper": "camper",
    "Campfire": "campfire",
    "Candy": "candy",
    "CandyCane": "candy-cane",
    "CandyOff": "candy-off",
    "Cannabis": "cannabis",
    "Cap": "cap",
    "Capcut": "capcut",
    "CapcutRectangle": "capcut-rectangle",
    "Car01": "car-01",
    "Car02": "car-02",
    "Car03": "car-03",
    "Car04": "car-04",
    "Car05": "car-05",
    "CarAlert": "car-alert",
    "CarFront": "car-front",
    "CarParking01": "car-parking-01",
    "CarParking02": "car-parking-02",
    "CarSignal": "car-signal",
    "CarTaxiFront": "car-taxi-front",
    "CarTime": "car-time",
    "Caravan": "caravan",
    "Cardigan": "cardigan",
    "Cardiogram01": "cardiogram-01",
    "Cardiogram02": "cardiogram-02",
    "Cards01": "cards-01",
    "Cards02": "cards-02",
    "CargoShip": "cargo-ship",
    "Caring": "caring",
    "Carrot": "carrot",
    "CaseUpper": "case-upper",
    "Cash01": "cash-01",
    "Cast": "cast",
    "Castbox": "castbox",
    "Castle": "castle",
    "Castle01": "castle-01",
    "Cat": "cat",
    "Cells": "cells",
    "ChangeScreenMode": "change-screen-mode",
    "ChartAlt": "chart",
    "Chart03": "chart-03",
    "ChartAnalysis": "chart-analysis",
    "ChartAverage": "chart-average",
    "ChartCandle": "chart-candle",
    "ChartIncrease": "chart-increase",
    "ChartLineData01": "chart-line-data-01",
    "ChartLineData02": "chart-line-data-02",
    "ChartNoAxesColumnDecreasing": "chart-no-axes-column-decreasing",
    "ChartNoAxesColumnIncreasing": "chart-no-axes-column-increasing",
    "ChartRadar": "chart-radar",
    "ChatBot": "chat-bot",
    "ChatGpt": "chat-gpt",
    "Cheese": "cheese",
    "CheeseCake01": "cheese-cake-01",
    "CheeseCake02": "cheese-cake-02",
    "Chef": "chef",
    "ChefHat": "chef-hat",
    "Cherry": "cherry",
    "Chess01": "chess-01",
    "Chess02": "chess-02",
    "ChessBishop": "chess-bishop",
    "ChessKing": "chess-king",
    "ChessKnight": "chess-knight",
    "ChessPawn": "chess-pawn",
    "ChessQueen": "chess-queen",
    "ChessRook": "chess-rook",
    "ChickenThighs": "chicken-thighs",
    "Chimney": "chimney",
    "Chip02": "chip-02",
    "Chocolate": "chocolate",
    "Chopsticks": "chopsticks",
    "Chrome": "chrome",
    "Cigarette": "cigarette",
    "CigaretteOff": "cigarette-off",
    "CinnamonRoll": "cinnamon-roll",
    "Circle": "circle",
    "CircleDashed": "circle-dashed",
    "CircleDollarSign": "circle-dollar-sign",
    "CircleDot": "circle-dot",
    "CircleDotDashed": "circle-dot-dashed",
    "CircleParking": "circle-parking",
    "CircleParkingOff": "circle-parking-off",
    "CirclePower": "circle-power",
    "CircleSmall": "circle-small",
    "CircuitBoard": "circuit-board",
    "Citrus": "citrus",
    "City03": "city-03",
    "Claude": "claude",
    "Clinic": "clinic",
    "Clover": "clover",
    "Club": "club",
    "Clubs01": "clubs-01",
    "Clubs02": "clubs-02",
    "CodeFolder": "code-folder",
    "CodeXml": "code-xml",
    "Codepen": "codepen",
    "Codesandbox": "codesandbox",
    "Coffee01": "coffee-01",
    "Coffee02": "coffee-02",
    "Coffee03": "coffee-03",
    "CoffeeBeans": "coffee-beans",
    "Coinbase": "coinbase",
    "Coins01": "coins-01",
    "Colosseum": "colosseum",
    "Comet01": "comet-01",
    "Comet02": "comet-02",
    "ComingSoon02": "coming-soon-02",
    "Command": "command",
    "CommandLine": "command-line",
    "ComputerActivity": "computer-activity",
    "ComputerArrowDown": "computer-arrow-down",
    "ComputerArrowUp": "computer-arrow-up",
    "ComputerChartDown": "computer-chart-down",
    "ComputerChartUp": "computer-chart-up",
    "ComputerDollar": "computer-dollar",
    "ComputerProgramming01": "computer-programming-01",
    "ConciergeBell": "concierge-bell",
    "Configuration01": "configuration-01",
    "Configuration02": "configuration-02",
    "Confused": "confused",
    "Constellation": "constellation",
    "Contact": "contact",
    "ContactBook": "contact-book",
    "ContactRound": "contact-round",
    "ContainerTruck": "container-truck",
    "ContentWriting": "content-writing",
    "Contrast": "contrast",
    "CookBook": "cook-book",
    "Cookie": "cookie",
    "CookingPot": "cooking-pot",
    "Copilot": "copilot",
    "Corn": "corn",
    "Corporate": "corporate",
    "Cottage": "cottage",
    "CottonCandy": "cotton-candy",
    "Coupon03": "coupon-03",
    "Course": "course",
    "CovidInfo": "covid-info",
    "Crab": "crab",
    "Crane": "crane",
    "CraneTower": "crane-tower",
    "Crazy": "crazy",
    "CreativeCommons": "creative-commons",
    "CreativeMarket": "creative-market",
    "CreditCard": "credit-card",
    "CricketBat": "cricket-bat",
    "CricketHelmet": "cricket-helmet",
    "Croissant": "croissant",
    "Cross": "cross",
    "Crying": "crying",
    "Css3": "css-3",
    "CupSoda": "cup-soda",
    "Cupcake01": "cupcake-01",
    "Cupcake02": "cupcake-02",
    "Cupcake03": "cupcake-03",
    "Curling": "curling",
    "CustomField": "custom-field",
    "CustomerService01": "customer-service-01",
    "CustomerService02": "customer-service-02",
    "CustomerSupport": "customer-support",
    "Customize": "customize",
    "Dart": "dart",
    "Datev": "datev",
    "Dead": "dead",
    "Deepseek": "deepseek",
    "DeliverySent01": "delivery-sent-01",
    "DeliveryTruck01": "delivery-truck-01",
    "DeliveryTruck02": "delivery-truck-02",
    "DentalBraces": "dental-braces",
    "DentalBrokenTooth": "dental-broken-tooth",
    "DentalCare": "dental-care",
    "DentalTooth": "dental-tooth",
    "Dessert": "dessert",
    "Detergent": "detergent",
    "Deviantart": "deviantart",
    "Diamond": "diamond",
    "Diamond01": "diamond-01",
    "Diamond02": "diamond-02",
    "DiamondPercent": "diamond-percent",
    "Dice": "dice",
    "DiceFaces01": "dice-faces-01",
    "DiceFaces02": "dice-faces-02",
    "DiceFaces03": "dice-faces-03",
    "DiceFaces04": "dice-faces-04",
    "DiceFaces05": "dice-faces-05",
    "DiceFaces06": "dice-faces-06",
    "Dices": "dices",
    "Digestion": "digestion",
    "Digg": "digg",
    "DigitalClock": "digital-clock",
    "DimSum01": "dim-sum-01",
    "DimSum02": "dim-sum-02",
    "Disability01": "disability-01",
    "Disability02": "disability-02",
    "Disc": "disc",
    "Disc2": "disc-2",
    "Discord": "discord",
    "Discount": "discount",
    "Discount01": "discount-01",
    "DiscountTag01": "discount-tag-01",
    "Dish01": "dish-01",
    "Dish02": "dish-02",
    "DishWasher": "dish-washer",
    "Displeased": "displeased",
    "DistributeHorizontalCenter": "distribute-horizontal-center",
    "Dna01": "dna-01",
    "DnaOff": "dna-off",
    "Doctor01": "doctor-01",
    "Doctor02": "doctor-02",
    "Doctor03": "doctor-03",
    "Dollar02": "dollar-02",
    "DollarSign": "dollar-sign",
    "Domino": "domino",
    "Donut": "donut",
    "Doughnut": "doughnut",
    "Download02": "download-02",
    "Download03": "download-03",
    "DraftingCompass": "drafting-compass",
    "DragDrop": "drag-drop",
    "DragDropHorizontal": "drag-drop-horizontal",
    "DragDropVertical": "drag-drop-vertical",
    "Drama": "drama",
    "DrawingCompass": "drawing-compass",
    "DrawingMode": "drawing-mode",
    "Dribbble": "dribbble",
    "Drill": "drill",
    "Drink": "drink",
    "Drone": "drone",
    "Drooling": "drooling",
    "Dropbox": "dropbox",
    "Droplet": "droplet",
    "Dropper": "dropper",
    "Drum": "drum",
    "Drumstick": "drumstick",
    "Ds3Tool": "ds3-tool",
    "Dumbbell01": "dumbbell-01",
    "Dumbbell02": "dumbbell-02",
    "Dumbbell03": "dumbbell-03",
    "DumpTruck": "dump-truck",
    "Ear": "ear",
    "EarOff": "ear-off",
    "Earth": "earth",
    "EarthLock": "earth-lock",
    "Eclipse": "eclipse",
    "EcoLab": "eco-lab",
    "EcoLab01": "eco-lab-01",
    "Edit02": "edit-02",
    "Egg": "egg",
    "EggFried": "egg-fried",
    "EggOff": "egg-off",
    "Eggs": "eggs",
    "EiffelTower": "eiffel-tower",
    "EightCircle": "eight-circle",
    "EightSquare": "eight-square",
    "Elder": "elder",
    "ElectricPlugs": "electric-plugs",
    "ElectricTower01": "electric-tower-01",
    "ElectricTower02": "electric-tower-02",
    "Ellipse": "ellipse",
    "Energy": "energy",
    "EnergyEllipse": "energy-ellipse",
    "Envato": "envato",
    "EquipmentBenchPress": "equipment-bench-press",
    "EquipmentChestPress": "equipment-chest-press",
    "EquipmentGym01": "equipment-gym-01",
    "EquipmentGym02": "equipment-gym-02",
    "EquipmentGym03": "equipment-gym-03",
    "EquipmentWeightlifting": "equipment-weightlifting",
    "EvCharger": "ev-charger",
    "EvCharging": "ev-charging",
    "Evil": "evil",
    "Expander": "expander",
    "Eye": "eye",
    "EyeClosed": "eye-closed",
    "EyeOff": "eye-off",
    "FaceId": "face-id",
    "Facebook01": "facebook-01",
    "Facebook02": "facebook-02",
    "Factory": "factory",
    "Factory01": "factory-01",
    "Factory02": "factory-02",
    "FallingStar": "falling-star",
    "Fan02": "fan-02",
    "Feather": "feather",
    "Fencing": "fencing",
    "FencingMask": "fencing-mask",
    "FerryBoat": "ferry-boat",
    "Figma": "figma",
    "FingerAccess": "finger-access",
    "FingerprintPattern": "fingerprint-pattern",
    "Fins": "fins",
    "Fire": "fire",
    "Fire02": "fire-02",
    "FireExtinguisher": "fire-extinguisher",
    "FirstAidKit": "first-aid-kit",
    "Fish": "fish",
    "FishFood": "fish-food",
    "FishOff": "fish-off",
    "FishSymbol": "fish-symbol",
    "FishingHook": "fishing-hook",
    "FishingRod": "fishing-rod",
    "FiveCircle": "five-circle",
    "FiveSquare": "five-square",
    "Fiverr": "fiverr",
    "FlameKindling": "flame-kindling",
    "Flashlight": "flashlight",
    "FlaskConical": "flask-conical",
    "FlaskConicalOff": "flask-conical-off",
    "FlaskRound": "flask-round",
    "Flaticon": "flaticon",
    "Flickr": "flickr",
    "FlipPhone": "flip-phone",
    "FloppyDisk": "floppy-disk",
    "Flower": "flower",
    "Flower01": "flower-01",
    "Flushed": "flushed",
    "FlyingHuman": "flying-human",
    "Folder02": "folder-02",
    "Folder03": "folder-03",
    "FolderAdd": "folder-add",
    "FolderArchive": "folder-archive",
    "FolderAttachment": "folder-attachment",
    "FolderAudio": "folder-audio",
    "FolderBlock": "folder-block",
    "FolderCheck": "folder-check",
    "FolderClock": "folder-clock",
    "FolderClosed": "folder-closed",
    "FolderCloud": "folder-cloud",
    "FolderCode": "folder-code",
    "FolderCog": "folder-cog",
    "FolderDetails": "folder-details",
    "FolderDetailsReference": "folder-details-reference",
    "FolderDown": "folder-down",
    "FolderDownload": "folder-download",
    "FolderEdit": "folder-edit",
    "FolderExport": "folder-export",
    "FolderFavourite": "folder-favourite",
    "FolderFileStorage": "folder-file-storage",
    "FolderGit": "folder-git",
    "FolderGit2": "folder-git-2",
    "FolderHeart": "folder-heart",
    "FolderImport": "folder-import",
    "FolderInput": "folder-input",
    "FolderKey": "folder-key",
    "FolderLibrary": "folder-library",
    "FolderLinks": "folder-links",
    "FolderLock": "folder-lock",
    "FolderLocked": "folder-locked",
    "FolderManagement": "folder-management",
    "FolderMinus": "folder-minus",
    "FolderMusic": "folder-music",
    "FolderOff": "folder-off",
    "FolderOpen": "folder-open",
    "FolderOpenDot": "folder-open-dot",
    "FolderOutput": "folder-output",
    "FolderPen": "folder-pen",
    "FolderPin": "folder-pin",
    "FolderPlus": "folder-plus",
    "FolderRemove": "folder-remove",
    "FolderRoot": "folder-root",
    "FolderSearch": "folder-search",
    "FolderSearch2": "folder-search-2",
    "FolderSecurity": "folder-security",
    "FolderShared01": "folder-shared-01",
    "FolderShared02": "folder-shared-02",
    "FolderShared03": "folder-shared-03",
    "FolderUnknown": "folder-unknown",
    "FolderUnlocked": "folder-unlocked",
    "FolderUp": "folder-up",
    "FolderUpload": "folder-upload",
    "FolderVideo": "folder-video",
    "FolderView": "folder-view",
    "Football": "football",
    "FootballPitch": "football-pitch",
    "Footprints": "footprints",
    "Fork": "fork",
    "Forklift": "forklift",
    "Forrst": "forrst",
    "Fortress": "fortress",
    "FourCircle": "four-circle",
    "FourSquare": "four-square",
    "Foursquare": "foursquare",
    "Framer": "framer",
    "FrenchFries01": "french-fries-01",
    "FrenchFries02": "french-fries-02",
    "Fridge": "fridge",
    "Frisbee": "frisbee",
    "Frown": "frown",
    "Fry": "fry",
    "Fuel": "fuel",
    "Fuel01": "fuel-01",
    "FuelStation": "fuel-station",
    "FullScreen": "full-screen",
    "Galaxy": "galaxy",
    "GameAlt": "game",
    "GameController01": "game-controller-01",
    "GameController02": "game-controller-02",
    "Gameboy": "gameboy",
    "Gamepad": "gamepad",
    "Gamepad01": "gamepad-01",
    "GamepadDirectional": "gamepad-directional",
    "GarbageTruck": "garbage-truck",
    "GasPipe": "gas-pipe",
    "GasStove": "gas-stove",
    "Gavel": "gavel",
    "Gears": "gears",
    "Gem": "gem",
    "GeologyCrust": "geology-crust",
    "GeometricShapes01": "geometric-shapes-01",
    "GeometricShapes02": "geometric-shapes-02",
    "Ghost": "ghost",
    "Gift": "gift",
    "Gitbook": "gitbook",
    "Github01": "github-01",
    "GiveBlood": "give-blood",
    "GivePill": "give-pill",
    "GlassWater": "glass-water",
    "Glasses": "glasses",
    "Global": "global",
    "Glove": "glove",
    "Gnome": "gnome",
    "GolfBall": "golf-ball",
    "GolfBat": "golf-bat",
    "GolfCart": "golf-cart",
    "GolfHole": "golf-hole",
    "Google": "google",
    "GoogleDoc": "google-doc",
    "GoogleDrive": "google-drive",
    "GoogleGemini": "google-gemini",
    "GoogleHome": "google-home",
    "GoogleLens": "google-lens",
    "GoogleMaps": "google-maps",
    "GooglePhotos": "google-photos",
    "GoogleSheet": "google-sheet",
    "GraduateFemale": "graduate-female",
    "GraduateMale": "graduate-male",
    "GraduationCap": "graduation-cap",
    "GraduationScroll": "graduation-scroll",
    "Grape": "grape",
    "Grapes": "grapes",
    "Gravity": "gravity",
    "GreekHelmet": "greek-helmet",
    "GreenHouse": "green-house",
    "Grid": "grid",
    "Grid02": "grid-02",
    "GridTable": "grid-table",
    "GridView": "grid-view",
    "Grid2x2": "grid2x2",
    "Grimacing": "grimacing",
    "Grinning": "grinning",
    "Grok": "grok",
    "Grok02": "grok-02",
    "GuestHouse": "guest-house",
    "Guitar": "guitar",
    "Gun": "gun",
    "Gymnastic": "gymnastic",
    "GymnasticRings": "gymnastic-rings",
    "Hackerrank": "hackerrank",
    "HalalLab": "halal-lab",
    "Ham": "ham",
    "Hamburger01": "hamburger-01",
    "Hamburger02": "hamburger-02",
    "HandBeater": "hand-beater",
    "HandGrab": "hand-grab",
    "HandGrip": "hand-grip",
    "HandHeart": "hand-heart",
    "HandMetal": "hand-metal",
    "HandPlatter": "hand-platter",
    "HandSanitizer": "hand-sanitizer",
    "Handbag": "handbag",
    "Handshake": "handshake",
    "Hangout": "hangout",
    "Happy": "happy",
    "Happy01": "happy-01",
    "HardDriveDownload": "hard-drive-download",
    "HardDriveUpload": "hard-drive-upload",
    "HardHat": "hard-hat",
    "Hash": "hash",
    "Hashtag": "hashtag",
    "HatGlasses": "hat-glasses",
    "Haze": "haze",
    "Hd": "hd",
    "Heading02": "heading-02",
    "Headphones": "headphones",
    "Healtcare": "healtcare",
    "Health": "health",
    "HeartPulse": "heart-pulse",
    "Helicopter": "helicopter",
    "Hexagon": "hexagon",
    "Highlighter": "highlighter",
    "Hiking": "hiking",
    "Hockey": "hockey",
    "Home07": "home-07",
    "Home10": "home-10",
    "Home11": "home-11",
    "Home12": "home-12",
    "Honey01": "honey-01",
    "Honey02": "honey-02",
    "Hop": "hop",
    "HopOff": "hop-off",
    "Horse": "horse",
    "HorseHead": "horse-head",
    "HorseSaddle": "horse-saddle",
    "Hospital01": "hospital-01",
    "Hospital02": "hospital-02",
    "HospitalBed01": "hospital-bed-01",
    "HospitalBed02": "hospital-bed-02",
    "HospitalLocation": "hospital-location",
    "HotAirBalloon": "hot-air-balloon",
    "Hotdog": "hotdog",
    "Hourglass": "hourglass",
    "HourglassOff": "hourglass-off",
    "House01": "house-01",
    "House03": "house-03",
    "Html5": "html-5",
    "Hugeicons": "hugeicons",
    "Hut": "hut",
    "IceCream01": "ice-cream-01",
    "IceCream02": "ice-cream-02",
    "IceCream03": "ice-cream-03",
    "IceCream04": "ice-cream-04",
    "IceCreamBowl": "ice-cream-bowl",
    "IceCreamCone": "ice-cream-cone",
    "IceCubes": "ice-cubes",
    "IceHockey": "ice-hockey",
    "IceSkating": "ice-skating",
    "Iconjar": "iconjar",
    "Idea01": "idea-01",
    "Imo": "imo",
    "InLove": "in-love",
    "Infant": "infant",
    "Injection": "injection",
    "Instagram": "instagram",
    "Invoice04": "invoice-04",
    "Ipod": "ipod",
    "Island": "island",
    "Jar": "jar",
    "Joker": "joker",
    "Joystick01": "joystick-01",
    "Joystick02": "joystick-02",
    "Joystick03": "joystick-03",
    "Joystick04": "joystick-04",
    "Joystick05": "joystick-05",
    "Jsx01": "jsx-01",
    "Jupiter": "jupiter",
    "Kayak": "kayak",
    "Kettle": "kettle",
    "Kettle01": "kettle-01",
    "Kettlebell": "kettlebell",
    "Key01": "key-01",
    "Key02": "key-02",
    "KeyRound": "key-round",
    "KeySquare": "key-square",
    "Kickstarter01": "kickstarter-01",
    "Kickstarter02": "kickstarter-02",
    "Kid": "kid",
    "Kidneys": "kidneys",
    "KimiAi": "kimi-ai",
    "Kissing": "kissing",
    "KitchenUtensils": "kitchen-utensils",
    "Kite": "kite",
    "Klarna": "klarna",
    "Knife01": "knife-01",
    "Knife02": "knife-02",
    "KnifeBread": "knife-bread",
    "KnightShield": "knight-shield",
    "Knives": "knives",
    "KoFi": "ko-fi",
    "Labor": "labor",
    "Labs": "labs",
    "Lake": "lake",
    "LampDesk": "lamp-desk",
    "Languages": "languages",
    "Laptop": "laptop",
    "LaptopIssue": "laptop-issue",
    "LaptopMinimal": "laptop-minimal",
    "LaptopMinimalCheck": "laptop-minimal-check",
    "LaptopPerformance": "laptop-performance",
    "LaptopPhoneSync": "laptop-phone-sync",
    "Lasso": "lasso",
    "LassoSelect": "lasso-select",
    "LassoTool01": "lasso-tool-01",
    "LassoTool02": "lasso-tool-02",
    "LastFm": "last-fm",
    "Laugh": "laugh",
    "Laughing": "laughing",
    "Layer": "layer",
    "LayersLogo": "layers-logo",
    "LayoutDashboard": "layout-dashboard",
    "LeafyGreen": "leafy-green",
    "Leetcode": "leetcode",
    "LensConcave": "lens-concave",
    "LensConvex": "lens-convex",
    "Libraries": "libraries",
    "Library": "library",
    "LibraryBig": "library-big",
    "LiftTruck": "lift-truck",
    "Lightbulb": "lightbulb",
    "Lighthouse": "lighthouse",
    "Line": "line",
    "Linkedin01": "linkedin-01",
    "Linkedin02": "linkedin-02",
    "ListVideo": "list-video",
    "Liver": "liver",
    "LoaderPinwheel": "loader-pinwheel",
    "Loading01": "loading-01",
    "Location08": "location-08",
    "Location09": "location-09",
    "LocationFavourite01": "location-favourite-01",
    "LocationShare01": "location-share-01",
    "LocationShare02": "location-share-02",
    "LocationStar01": "location-star-01",
    "LocationStar02": "location-star-02",
    "LockKeyholeOpen": "lock-keyhole-open",
    "LockOpen": "lock-open",
    "LockPassword": "lock-password",
    "Locker": "locker",
    "Locker01": "locker-01",
    "Lollipop": "lollipop",
    "LookBottom": "look-bottom",
    "LookLeft": "look-left",
    "LookRight": "look-right",
    "LookTop": "look-top",
    "Loom": "loom",
    "Lottiefiles": "lottiefiles",
    "Luggage01": "luggage-01",
    "Luggage02": "luggage-02",
    "Lungs": "lungs",
    "MachineRobot": "machine-robot",
    "MagicWand01": "magic-wand-01",
    "MagicWand02": "magic-wand-02",
    "Magnet": "magnet",
    "Manager": "manager",
    "Marketing": "marketing",
    "Mask": "mask",
    "MaskLove": "mask-love",
    "MaskTheater01": "mask-theater-01",
    "MaskTheater02": "mask-theater-02",
    "Mastodon": "mastodon",
    "Matches": "matches",
    "MayanPyramid": "mayan-pyramid",
    "Maze": "maze",
    "McpServer": "mcp-server",
    "MealScan": "meal-scan",
    "MedicalFile": "medical-file",
    "MedicalMask": "medical-mask",
    "Medicine01": "medicine-01",
    "Medicine02": "medicine-02",
    "MedicineBottle01": "medicine-bottle-01",
    "MedicineBottle02": "medicine-bottle-02",
    "MedicineSyrup": "medicine-syrup",
    "Medium": "medium",
    "MediumSquare": "medium-square",
    "Megaphone01": "megaphone-01",
    "Megaphone02": "megaphone-02",
    "Meh": "meh",
    "MemoryStick": "memory-stick",
    "MessageEdit01": "message-edit-01",
    "MessageFavourite01": "message-favourite-01",
    "MessageSearch02": "message-search-02",
    "MessageSquareHeart": "message-square-heart",
    "MessageSquareWarning": "message-square-warning",
    "MessageUnlock01": "message-unlock-01",
    "MessageUnlock02": "message-unlock-02",
    "MessageUpload01": "message-upload-01",
    "MessageUpload02": "message-upload-02",
    "MessageUser01": "message-user-01",
    "MessageUser02": "message-user-02",
    "MessagesSquare": "messages-square",
    "Messenger": "messenger",
    "Meta": "meta",
    "Metro": "metro",
    "Metronome": "metronome",
    "Mic02": "mic-02",
    "MicVocal": "mic-vocal",
    "Microchip": "microchip",
    "Microscope": "microscope",
    "Microsoft": "microsoft",
    "Microwave": "microwave",
    "Milk": "milk",
    "MilkBottle": "milk-bottle",
    "MilkCarton": "milk-carton",
    "MilkCoconut": "milk-coconut",
    "MilkOat": "milk-oat",
    "MilkOff": "milk-off",
    "Mistral": "mistral",
    "Mixer": "mixer",
    "Mochi": "mochi",
    "ModernTv": "modern-tv",
    "ModernTv4K": "modern-tv-4-k",
    "ModernTvIssue": "modern-tv-issue",
    "Molecules": "molecules",
    "Mollie": "mollie",
    "Monas": "monas",
    "MoneyBag01": "money-bag-01",
    "MoneyBag02": "money-bag-02",
    "Monitor": "monitor",
    "MonitorCheck": "monitor-check",
    "MonitorCloud": "monitor-cloud",
    "MonitorCog": "monitor-cog",
    "MonitorDot": "monitor-dot",
    "MonitorSpeaker": "monitor-speaker",
    "Monocle01": "monocle-01",
    "Monster": "monster",
    "Moon": "moon",
    "MoonLanding": "moon-landing",
    "Mortar": "mortar",
    "Mosque04": "mosque-04",
    "Mosque05": "mosque-05",
    "Motorbike01": "motorbike-01",
    "Motorbike02": "motorbike-02",
    "Mountain": "mountain",
    "MountainSnow": "mountain-snow",
    "Mouse03": "mouse-03",
    "Mouse05": "mouse-05",
    "Mouse11": "mouse-11",
    "Mouse13": "mouse-13",
    "Mouse15": "mouse-15",
    "Mouse16": "mouse-16",
    "Mouse19": "mouse-19",
    "Mouse23": "mouse-23",
    "Mushroom": "mushroom",
    "Mushroom01": "mushroom-01",
    "Music02": "music-02",
    "Music3": "music-3",
    "MusicNote03": "music-note-03",
    "MusicNote04": "music-note-04",
    "Mute": "mute",
    "Mymind": "mymind",
    "NanoTechnology": "nano-technology",
    "Napkins01": "napkins-01",
    "Napkins02": "napkins-02",
    "NaturalFood": "natural-food",
    "Navigation03": "navigation-03",
    "Navigation05": "navigation-05",
    "Navigation06": "navigation-06",
    "Navigation07": "navigation-07",
    "Nerd": "nerd",
    "Neutral": "neutral",
    "NewTwitter": "new-twitter",
    "NewTwitterEllipse": "new-twitter-ellipse",
    "NewTwitterRectangle": "new-twitter-rectangle",
    "Nike": "nike",
    "Nintendo": "nintendo",
    "NintendoSwitch": "nintendo-switch",
    "Noodles": "noodles",
    "Nose": "nose",
    "Notion01": "notion-01",
    "Notion02": "notion-02",
    "Npm": "npm",
    "NuclearPower": "nuclear-power",
    "Nut": "nut",
    "NutOff": "nut-off",
    "Octopus": "octopus",
    "Office365": "office-365",
    "OilBarrel": "oil-barrel",
    "OlympicTorch": "olympic-torch",
    "Orange": "orange",
    "Orbit01": "orbit-01",
    "Orbit02": "orbit-02",
    "OrganicFood": "organic-food",
    "Origami": "origami",
    "Oval": "oval",
    "Oven": "oven",
    "Package": "package",
    "PackageMoving": "package-moving",
    "PackageMoving01": "package-moving-01",
    "Packaging": "packaging",
    "Pacman01": "pacman-01",
    "Pacman02": "pacman-02",
    "Paella": "paella",
    "PaintBrush01": "paint-brush-01",
    "PaintBrush02": "paint-brush-02",
    "PaintBrush03": "paint-brush-03",
    "PaintBrush04": "paint-brush-04",
    "PaintBucket": "paint-bucket",
    "PaintRoller": "paint-roller",
    "Paintbrush": "paintbrush",
    "PaintbrushVertical": "paintbrush-vertical",
    "Palette": "palette",
    "Pan01": "pan-01",
    "Pan02": "pan-02",
    "Pan03": "pan-03",
    "Panda": "panda",
    "Paragliding": "paragliding",
    "ParkingAreaCircle": "parking-area-circle",
    "ParkingAreaSquare": "parking-area-square",
    "ParkingMeter": "parking-meter",
    "Party": "party",
    "PartyPopper": "party-popper",
    "Passport": "passport",
    "Path": "path",
    "Patient": "patient",
    "PawPrint": "paw-print",
    "Payoneer": "payoneer",
    "Paypal": "paypal",
    "PcCase": "pc-case",
    "Pen02": "pen-02",
    "PenTool01": "pen-tool-01",
    "PenTool02": "pen-tool-02",
    "PenTool03": "pen-tool-03",
    "Pencil": "pencil",
    "PencilEdit02": "pencil-edit-02",
    "Pendulum": "pendulum",
    "Pensive": "pensive",
    "Pentagon": "pentagon",
    "Pepper": "pepper",
    "Periscope": "periscope",
    "PersonStanding": "person-standing",
    "PetrolPump": "petrol-pump",
    "Pexels": "pexels",
    "Picasa": "picasa",
    "Pickup01": "pickup-01",
    "Pickup02": "pickup-02",
    "PictureInPicture01": "picture-in-picture-01",
    "Pie": "pie",
    "Pill": "pill",
    "PillBottle": "pill-bottle",
    "PillOff": "pill-off",
    "PillsTablet": "pills-tablet",
    "Pin": "pin",
    "PinLocation03": "pin-location-03",
    "PineTree": "pine-tree",
    "Pinterest": "pinterest",
    "Pipette": "pipette",
    "PisaTower": "pisa-tower",
    "Pizza01": "pizza-01",
    "Pizza02": "pizza-02",
    "Pizza03": "pizza-03",
    "Pizza04": "pizza-04",
    "PizzaCutter": "pizza-cutter",
    "Plane": "plane",
    "PlaneLanding": "plane-landing",
    "PlaneTakeoff": "plane-takeoff",
    "Plant01": "plant-01",
    "Plant02": "plant-02",
    "Plate": "plate",
    "Plaxo": "plaxo",
    "PlayStore": "play-store",
    "Plaza": "plaza",
    "Plug": "plug",
    "Plug02": "plug-02",
    "Plug03": "plug-03",
    "Pocket": "pocket",
    "PocketKnife": "pocket-knife",
    "Pokeball": "pokeball",
    "Pokemon": "pokemon",
    "PoliceCar": "police-car",
    "Polygon": "polygon",
    "Pool": "pool",
    "PoolTable": "pool-table",
    "Popcorn": "popcorn",
    "Popsicle": "popsicle",
    "Pot01": "pot-01",
    "Pot02": "pot-02",
    "Potion": "potion",
    "PowerService": "power-service",
    "PowerSocket01": "power-socket-01",
    "Prawn": "prawn",
    "Prescription": "prescription",
    "Prescriptions": "prescriptions",
    "Presentation01": "presentation-01",
    "Presentation03": "presentation-03",
    "Presentation04": "presentation-04",
    "Presentation05": "presentation-05",
    "PresentationOnline": "presentation-online",
    "Prism01": "prism-01",
    "Projector": "projector",
    "Promotion": "promotion",
    "ProtectionMask": "protection-mask",
    "Pulley": "pulley",
    "Pulse01": "pulse-01",
    "Pulse02": "pulse-02",
    "PulseRectangle01": "pulse-rectangle-01",
    "PulseRectangle02": "pulse-rectangle-02",
    "Pumpkin": "pumpkin",
    "PunchingBall01": "punching-ball-01",
    "PunchingBall02": "punching-ball-02",
    "PushUpBar": "push-up-bar",
    "Puzzle": "puzzle",
    "Python": "python",
    "QuillWrite01": "quill-write-01",
    "Quiz01": "quiz-01",
    "Quora": "quora",
    "Qwen": "qwen",
    "Rabbit": "rabbit",
    "RacingFlag": "racing-flag",
    "Radar03": "radar-03",
    "Radial": "radial",
    "Radiation": "radiation",
    "RailSymbol": "rail-symbol",
    "Rain": "rain",
    "RainDoubleDrop": "rain-double-drop",
    "Rat": "rat",
    "React": "react",
    "RectangleHorizontal": "rectangle-horizontal",
    "RectangleVertical": "rectangle-vertical",
    "Rectangular": "rectangular",
    "Recycle02": "recycle-02",
    "Reddit": "reddit",
    "Redo": "redo",
    "Redo02": "redo-02",
    "RefreshCw": "refresh-cw",
    "Refrigerator": "refrigerator",
    "Relieved01": "relieved-01",
    "Relieved02": "relieved-02",
    "RenewableEnergy01": "renewable-energy-01",
    "Replit": "replit",
    "Restaurant01": "restaurant-01",
    "Restaurant02": "restaurant-02",
    "Restaurant03": "restaurant-03",
    "ReverseWithdrawal01": "reverse-withdrawal-01",
    "Rhombus": "rhombus",
    "Ribbon": "ribbon",
    "RiceBowl01": "rice-bowl-01",
    "RiceBowl02": "rice-bowl-02",
    "Road": "road",
    "Roblox": "roblox",
    "Robot01": "robot-01",
    "Robot02": "robot-02",
    "Robotic": "robotic",
    "RocketAlt": "rocket",
    "Rocket02": "rocket-02",
    "RockingHorse": "rocking-horse",
    "RollerCoaster": "roller-coaster",
    "RollerSkate": "roller-skate",
    "RollingPin": "rolling-pin",
    "Rotate02": "rotate-02",
    "RubberDuck": "rubber-duck",
    "RubiksCube": "rubiks-cube",
    "RunningShoes": "running-shoes",
    "Sad01": "sad-01",
    "Sad02": "sad-02",
    "SadDizzy": "sad-dizzy",
    "Safari": "safari",
    "Safe": "safe",
    "SafeBox": "safe-box",
    "Sailboat": "sailboat",
    "SailboatOffshore": "sailboat-offshore",
    "Salad": "salad",
    "SaleTag01": "sale-tag-01",
    "SaleTag02": "sale-tag-02",
    "Sandwich": "sandwich",
    "Satellite01": "satellite-01",
    "Satellite02": "satellite-02",
    "Saturn": "saturn",
    "Saturn01": "saturn-01",
    "Saturn02": "saturn-02",
    "Sausage": "sausage",
    "SaveEnergy01": "save-energy-01",
    "SaveMoneyDollar": "save-money-dollar",
    "Savings": "savings",
    "Scale": "scale",
    "ScanFace": "scan-face",
    "ScanHeart": "scan-heart",
    "School01": "school-01",
    "SchoolBus": "school-bus",
    "ScissorsAlt": "scissors",
    "Scooter01": "scooter-01",
    "Scooter02": "scooter-02",
    "Scooter03": "scooter-03",
    "Scooter04": "scooter-04",
    "ScooterElectric": "scooter-electric",
    "ScratchCard": "scratch-card",
    "Scribd": "scribd",
    "Seal": "seal",
    "SeatSelector": "seat-selector",
    "SecurityPassword": "security-password",
    "Seesaw": "seesaw",
    "SelfTransfer": "self-transfer",
    "SemiTruck": "semi-truck",
    "Send": "send",
    "SendHorizontal": "send-horizontal",
    "SendingOrder": "sending-order",
    "Senseless": "senseless",
    "Sent": "sent",
    "Sent02": "sent-02",
    "ServingFood": "serving-food",
    "Shadcn": "shadcn",
    "ShadcnSquare": "shadcn-square",
    "Shapes": "shapes",
    "Shapes01": "shapes-01",
    "SharedDrive": "shared-drive",
    "Shell": "shell",
    "Shellfish": "shellfish",
    "ShieldAlert": "shield-alert",
    "Ship": "ship",
    "ShipWheel": "ship-wheel",
    "ShippingCenter": "shipping-center",
    "Shirt01": "shirt-01",
    "Shocked": "shocked",
    "Shoes": "shoes",
    "Shopify": "shopify",
    "ShoppingBasket01": "shopping-basket-01",
    "ShoppingBasket03": "shopping-basket-03",
    "Shoulder": "shoulder",
    "Shrimp": "shrimp",
    "Shutterstock": "shutterstock",
    "SidebarBottom": "sidebar-bottom",
    "SidebarLeft": "sidebar-left",
    "SidebarRight": "sidebar-right",
    "SidebarTop": "sidebar-top",
    "Signal": "signal",
    "Silence": "silence",
    "SingLeft": "sing-left",
    "SingRight": "sing-right",
    "Siri": "siri",
    "SiriNew": "siri-new",
    "Sketch": "sketch",
    "Ski": "ski",
    "SkippingRope": "skipping-rope",
    "Skool": "skool",
    "Skype": "skype",
    "Slack": "slack",
    "Sleeping": "sleeping",
    "Slide": "slide",
    "Slideshare": "slideshare",
    "Smart": "smart",
    "SmartphoneCharging": "smartphone-charging",
    "Smile": "smile",
    "SmileDizzy": "smile-dizzy",
    "SmilePlus": "smile-plus",
    "Snail": "snail",
    "Snapchat": "snapchat",
    "Sneaker": "sneaker",
    "Snow": "snow",
    "Snowflake": "snowflake",
    "Socks": "socks",
    "SodaCan": "soda-can",
    "SoftDrink01": "soft-drink-01",
    "SoftDrink02": "soft-drink-02",
    "SolarSystem": "solar-system",
    "SolarSystem01": "solar-system-01",
    "Soundcloud": "soundcloud",
    "Soup": "soup",
    "Spaceship": "spaceship",
    "Spades": "spades",
    "Spaghetti": "spaghetti",
    "SpartanHelmet": "spartan-helmet",
    "Spatula": "spatula",
    "SpeakerAlt": "speaker",
    "SpeedTrain01": "speed-train-01",
    "SpeedTrain02": "speed-train-02",
    "Sperm": "sperm",
    "Spirals": "spirals",
    "Spool": "spool",
    "Spoon": "spoon",
    "SportShoe": "sport-shoe",
    "Spotify": "spotify",
    "Square": "square",
    "SquareM": "square-m",
    "SquareParking": "square-parking",
    "SquareParkingOff": "square-parking-off",
    "SquarePause": "square-pause",
    "SquarePower": "square-power",
    "SquareSplitVertical": "square-split-vertical",
    "SquareTerminal": "square-terminal",
    "SquareUserRound": "square-user-round",
    "SquircleDashed": "squircle-dashed",
    "Squirrel": "squirrel",
    "StarFace": "star-face",
    "StartUp01": "start-up-01",
    "StartUp02": "start-up-02",
    "Steak": "steak",
    "Steering": "steering",
    "Stethoscope": "stethoscope",
    "Stethoscope02": "stethoscope-02",
    "Sticker": "sticker",
    "Stone": "stone",
    "Stop": "stop",
    "StopCircle": "stop-circle",
    "StopWatch": "stop-watch",
    "StreetFood": "street-food",
    "Stripe": "stripe",
    "Student": "student",
    "StudentCard": "student-card",
    "Stumbleupon": "stumbleupon",
    "Submarine": "submarine",
    "Submerge": "submerge",
    "Sun01": "sun-01",
    "Sun03": "sun-03",
    "SunMoon": "sun-moon",
    "Sunglasses": "sunglasses",
    "SuperMario": "super-mario",
    "SuperMarioToad": "super-mario-toad",
    "Surfboard": "surfboard",
    "Surprise": "surprise",
    "Sushi01": "sushi-01",
    "Sushi02": "sushi-02",
    "Sushi03": "sushi-03",
    "Suspicious": "suspicious",
    "Swarm": "swarm",
    "Swimming": "swimming",
    "SwimmingCap": "swimming-cap",
    "SwitchCamera": "switch-camera",
    "Sword01": "sword-01",
    "Sword02": "sword-02",
    "Sword03": "sword-03",
    "Swords": "swords",
    "Syringe": "syringe",
    "TShirt": "t-shirt",
    "TableTennisBat": "table-tennis-bat",
    "Tablet02": "tablet-02",
    "TabletSmartphone": "tablet-smartphone",
    "Tablets": "tablets",
    "Taco01": "taco-01",
    "Taco02": "taco-02",
    "Tags": "tags",
    "Tailwindcss": "tailwindcss",
    "TajMahal": "taj-mahal",
    "TankerTruck": "tanker-truck",
    "TapeMeasure": "tape-measure",
    "Taxi": "taxi",
    "Taxi02": "taxi-02",
    "Tea": "tea",
    "TeaPod": "tea-pod",
    "Teamviewer": "teamviewer",
    "Technician": "technician",
    "Telegram": "telegram",
    "TennisBall": "tennis-ball",
    "TennisRacket": "tennis-racket",
    "Tent": "tent",
    "TestTube": "test-tube",
    "TestTube01": "test-tube-01",
    "TestTube02": "test-tube-02",
    "TestTube03": "test-tube-03",
    "TestTubeDiagonal": "test-tube-diagonal",
    "TestTubes": "test-tubes",
    "Tetris": "tetris",
    "Theater": "theater",
    "ThermometerSnowflake": "thermometer-snowflake",
    "ThermometerSun": "thermometer-sun",
    "Thread": "thread",
    "Threads": "threads",
    "ThreadsEllipse": "threads-ellipse",
    "ThreadsRectangle": "threads-rectangle",
    "TicTacToe": "tic-tac-toe",
    "Ticket01": "ticket-01",
    "Tiktok": "tiktok",
    "Tiltify": "tiltify",
    "Timer01": "timer-01",
    "Tire": "tire",
    "Tired01": "tired-01",
    "Tired02": "tired-02",
    "TissuePaper": "tissue-paper",
    "ToggleRight": "toggle-right",
    "Tongue": "tongue",
    "Tongue01": "tongue-01",
    "TongueWinkLeft": "tongue-wink-left",
    "TongueWinkRight": "tongue-wink-right",
    "ToolCase": "tool-case",
    "Toolbox": "toolbox",
    "Tools": "tools",
    "TorriGate": "torri-gate",
    "Torus": "torus",
    "TowTruck": "tow-truck",
    "TowelRack": "towel-rack",
    "Towels": "towels",
    "TowerControl": "tower-control",
    "ToyTrain": "toy-train",
    "Tractor": "tractor",
    "TrafficCone": "traffic-cone",
    "TrafficIncident": "traffic-incident",
    "TrafficJam01": "traffic-jam-01",
    "TrafficJam02": "traffic-jam-02",
    "TrafficLight": "traffic-light",
    "Train01": "train-01",
    "Train02": "train-02",
    "TrainFront": "train-front",
    "TrainFrontTunnel": "train-front-tunnel",
    "TrainTrack": "train-track",
    "Tram": "tram",
    "TramFront": "tram-front",
    "Trampoline": "trampoline",
    "Translation": "translation",
    "Transparency": "transparency",
    "Treadmill01": "treadmill-01",
    "Treadmill02": "treadmill-02",
    "Treatment": "treatment",
    "Tree06": "tree-06",
    "Tree07": "tree-07",
    "TreeDeciduous": "tree-deciduous",
    "TreePalm": "tree-palm",
    "Trello": "trello",
    "Triangle": "triangle",
    "Triangle03": "triangle-03",
    "TriangleDashed": "triangle-dashed",
    "Trolley01": "trolley-01",
    "Trolley02": "trolley-02",
    "Truck": "truck",
    "TruckDelivery": "truck-delivery",
    "TruckElectric": "truck-electric",
    "TruckMonster": "truck-monster",
    "TruckReturn": "truck-return",
    "Tumblr": "tumblr",
    "Turntable": "turntable",
    "Turtle": "turtle",
    "Tv01": "tv-01",
    "Tv02": "tv-02",
    "TvMinimal": "tv-minimal",
    "TwinTower": "twin-tower",
    "Twitch": "twitch",
    "Twitter": "twitter",
    "TwitterSquare": "twitter-square",
    "Typescript01": "typescript-01",
    "Uber": "uber",
    "Ufo": "ufo",
    "Ufo01": "ufo-01",
    "Umbrella": "umbrella",
    "Unamused": "unamused",
    "Underpants03": "underpants-03",
    "Unhappy": "unhappy",
    "UniversalAccess": "universal-access",
    "University": "university",
    "Unplug": "unplug",
    "Unsplash": "unsplash",
    "Upwork": "upwork",
    "Usb": "usb",
    "UsbMemory01": "usb-memory-01",
    "UsbMemory02": "usb-memory-02",
    "Utensils": "utensils",
    "UtensilsCrossed": "utensils-crossed",
    "Uv01": "uv-01",
    "Vaccine": "vaccine",
    "Van": "van",
    "VegetarianFood": "vegetarian-food",
    "VenetianMask": "venetian-mask",
    "Versus": "versus",
    "Viber": "viber",
    "VideoConsole": "video-console",
    "Videotape": "videotape",
    "View": "view",
    "ViewOff": "view-off",
    "ViewOffSlash": "view-off-slash",
    "Villa01": "villa-01",
    "Vimeo": "vimeo",
    "Vine": "vine",
    "VineSquare": "vine-square",
    "VirtualRealityVr01": "virtual-reality-vr-01",
    "VisualStudioCode": "visual-studio-code",
    "Vk": "vk",
    "VkSquare": "vk-square",
    "VoiceId": "voice-id",
    "Volleyball": "volleyball",
    "Vomiting": "vomiting",
    "Vr": "vr",
    "VrGlasses": "vr-glasses",
    "Vynil01": "vynil-01",
    "Vynil02": "vynil-02",
    "Vynil03": "vynil-03",
    "W3Schools": "w-3-schools",
    "Waiter": "waiter",
    "Walking": "walking",
    "Wallet01": "wallet-01",
    "Wallet02": "wallet-02",
    "Wallet03": "wallet-03",
    "Wallet05": "wallet-05",
    "WalletCards": "wallet-cards",
    "Wallpaper": "wallpaper",
    "Walpaper": "walpaper",
    "Wand": "wand",
    "WashingMachine": "washing-machine",
    "WashingtonMonument": "washington-monument",
    "Watch01": "watch-01",
    "Watch02": "watch-02",
    "WaterPolo": "water-polo",
    "Watermelon": "watermelon",
    "Wattpad": "wattpad",
    "WattpadSquare": "wattpad-square",
    "WavesLadder": "waves-ladder",
    "Waze": "waze",
    "Webflow": "webflow",
    "WebflowEllipse": "webflow-ellipse",
    "WebflowRectangle": "webflow-rectangle",
    "Webhook": "webhook",
    "WebhookOff": "webhook-off",
    "Wechat": "wechat",
    "Weight": "weight",
    "WeightScale": "weight-scale",
    "WeightScale01": "weight-scale-01",
    "WeightTilde": "weight-tilde",
    "Wellness": "wellness",
    "Whatsapp": "whatsapp",
    "WhatsappBusiness": "whatsapp-business",
    "Wheat": "wheat",
    "WheatOff": "wheat-off",
    "Wheelchair": "wheelchair",
    "Whisk": "whisk",
    "Whistle": "whistle",
    "Wikipedia": "wikipedia",
    "Wind": "wind",
    "WindPower01": "wind-power-01",
    "WindPower02": "wind-power-02",
    "WindPower03": "wind-power-03",
    "WindSurf": "wind-surf",
    "WindTurbine": "wind-turbine",
    "WindowsNew": "windows-new",
    "WindowsOld": "windows-old",
    "Wink": "wink",
    "Winking": "winking",
    "Wise": "wise",
    "Wordpress": "wordpress",
    "WorkoutBattleRopes": "workout-battle-ropes",
    "WorkoutGymnastics": "workout-gymnastics",
    "WorkoutKicking": "workout-kicking",
    "WorkoutRun": "workout-run",
    "WorkoutSport": "workout-sport",
    "WorkoutSquats": "workout-squats",
    "WorkoutStretching": "workout-stretching",
    "WorkoutWarmUp": "workout-warm-up",
    "Worm": "worm",
    "Worry": "worry",
    "WpsOffice": "wps-office",
    "WpsOfficeRectangle": "wps-office-rectangle",
    "Wrench01": "wrench-01",
    "Wrench02": "wrench-02",
    "XRay": "x-ray",
    "Xing": "xing",
    "Yelp": "yelp",
    "Yoga01": "yoga-01",
    "Yoga02": "yoga-02",
    "Yoga03": "yoga-03",
    "YogaBall": "yoga-ball",
    "YogaMat": "yoga-mat",
    "Yogurt": "yogurt",
    "Youtube": "youtube",
    "Yurt": "yurt",
    "Zap": "zap",
    "Zeppelin": "zeppelin",
    "ZodiacAquarius": "zodiac-aquarius",
    "ZodiacAries": "zodiac-aries",
    "ZodiacCancer": "zodiac-cancer",
    "ZodiacCapricorn": "zodiac-capricorn",
    "ZodiacGemini": "zodiac-gemini",
    "ZodiacLeo": "zodiac-leo",
    "ZodiacLibra": "zodiac-libra",
    "ZodiacOphiuchus": "zodiac-ophiuchus",
    "ZodiacPisces": "zodiac-pisces",
    "ZodiacSagittarius": "zodiac-sagittarius",
    "ZodiacScorpio": "zodiac-scorpio",
    "ZodiacTaurus": "zodiac-taurus",
    "ZodiacVirgo": "zodiac-virgo",
    "Zoom": "zoom",
    "ZoomCircle": "zoom-circle",
    "ZoomSquare": "zoom-square",
    "Zzz": "zzz",
}


def fetch(name: str) -> str:
    """The SVG source, from disk if it is already there."""
    cached = SOURCES / f"{name}.svg"

    if cached.exists():
        return cached.read_text(encoding="utf-8")

    # Iconify refuses the default urllib user agent with 403.
    request = urllib.request.Request(
        API.format(name=name),
        headers={"User-Agent": "master-control-dock/icon-fetch"},
    )

    with urllib.request.urlopen(request, timeout=30) as response:
        svg = response.read().decode("utf-8")

    SOURCES.mkdir(parents=True, exist_ok=True)
    cached.write_text(svg, encoding="utf-8")
    return svg


def _attrs(tag: str) -> dict[str, str]:
    return dict(re.findall(r'([a-zA-Z-]+)="([^"]*)"', tag))


def _shapes(svg: str) -> list[str]:
    """
    Every drawn element, as path data.

    Not every icon is made of paths. Several are drawn with <circle>,
    <ellipse> or <rect>, and a reader that only looks for d="..." throws those
    away without a word - which is how the network icon arrived as a single
    horizontal stroke where a globe should have been.
    """
    found: list[str] = []

    for match in re.finditer(r"<(path|circle|ellipse|rect|line|polyline|polygon)\b([^>]*)>", svg):
        kind, body = match.group(1), match.group(2)
        a = _attrs(body)

        if kind == "path":
            found.append(a["d"])

        elif kind in ("circle", "ellipse"):
            cx, cy = float(a.get("cx", 0)), float(a.get("cy", 0))
            rx = float(a.get("rx", a.get("r", 0)))
            ry = float(a.get("ry", a.get("r", 0)))

            # Two half-turns: one arc cannot describe a whole ellipse, because
            # its start and end points would coincide.
            found.append(
                f"M {cx - rx} {cy} A {rx} {ry} 0 1 0 {cx + rx} {cy} "
                f"A {rx} {ry} 0 1 0 {cx - rx} {cy} Z"
            )

        elif kind == "rect":
            x, y = float(a.get("x", 0)), float(a.get("y", 0))
            w, h = float(a["width"]), float(a["height"])
            found.append(f"M {x} {y} H {x + w} V {y + h} H {x} Z")

        elif kind == "line":
            found.append(
                f"M {float(a['x1'])} {float(a['y1'])} L {float(a['x2'])} {float(a['y2'])}"
            )

        else:
            points = re.findall(r"[-+0-9.eE]+", a["points"])
            pairs = list(zip(points[0::2], points[1::2]))
            body = " L ".join(f"{x} {y}" for x, y in pairs[1:])
            close = " Z" if kind == "polygon" else ""
            found.append(f"M {pairs[0][0]} {pairs[0][1]} L {body}{close}")

    return found


def combine(svg: str) -> str:
    """
    Every shape in one string.

    All of them are strokes of the same width in the same group, so joining them
    loses nothing. They differ only in their line cap, and round caps throughout
    read better at fifteen pixels than the mixture does.
    """
    shapes = _shapes(svg)

    if not shapes:
        raise ValueError("nothing drawn in the icon")

    # Normalised, because WinUI reads the same commands as SVG but not the
    # compressed spelling Iconify serves. See tools/svgpath.py.
    return grown(" ".join(normalise(s.strip()) for s in shapes))


# The grid the icons are drawn on, and the live area they should fill on it.
GRID = 24.0
LIVE = 20.0

# Never more than this. A drawing measured small because it is genuinely small
# is one thing; a measurement that went wrong is another, and half again is as
# far as the first can honestly need.
MOST = 1.45


def grown(data: str) -> str:
    """
    The same drawing, enlarged to fill the grid the way its neighbours do.

    The set is not drawn to one size. Measured, the arrows fill twelve units by
    fourteen where the processor fills twenty by twenty - so on a bar where the
    two stand side by side one reads as a smaller, lighter icon than the other,
    at the same nominal size and the same stroke.

    The measurement over-estimates, never under: a curve stays inside the box
    of its control points, and an arc inside the radii round its ends. That
    only ever asks for less enlargement than the drawing could take, so nothing
    can be pushed off the grid by a measurement that went wide.
    """
    left, top, right, bottom = extent(data)
    widest = max(right - left, bottom - top)

    if widest <= 0:
        return data

    factor = min(MOST, LIVE / widest)

    # And never past the edge of the grid. A drawing is enlarged about the
    # middle, and one that does not sit in the middle has a far edge that
    # moves further than its near one - which pushed the thermometer, a tall
    # drawing hung low, out of the square it is drawn in.
    middle = GRID / 2

    for edge in (left, top, right, bottom):
        room = (GRID - middle) if edge > middle else (0 - middle)
        reach = edge - middle

        if abs(reach) > 0.01:
            factor = min(factor, room / reach)

    return data if factor <= 1.01 else scale(data, factor, middle)


def _self_check() -> None:
    """
    A handful of shapes that used to come out wrong.

    Every one of these was a real bug, and every one of them was invisible in
    the code and obvious on screen. They cost a rebuild and a squint each time,
    so they are checked here instead.
    """
    # Arc flags run together with the coordinates after them.
    assert normalise("a2 2 0 100-4") == "a 2 2 0 1 0 0 -4"

    # A path's own first moveto is absolute, and stays absolute when joined.
    assert normalise("m5 5l1 1").startswith("M 5 5")

    # A repeated moveto is a lineto.
    assert normalise("M1 1 2 2") == "M 1 1 L 2 2"

    # Circles and ellipses are shapes too, not just paths.
    assert "A 10 10" in combine('<circle cx="12" cy="12" r="10"/>')
    assert "A 4 10" in combine('<ellipse cx="12" cy="12" rx="4" ry="10"/>')

    # A drawing that already fills the grid is left alone; a small one grows
    # about the middle and stays inside the grid.
    assert grown("M 2 2 L 22 2") == "M 2 2 L 22 2"

    # Sixteen units across grows by a quarter, about the middle of the grid.
    small = grown("M 4 12 L 20 12")
    assert small == "M 2 12 L 22 12", small


def main() -> None:
    _self_check()

    rows: list[str] = []

    for key, name in ICONS.items():
        data = combine(fetch(name))
        rows.append(f'        ["{key}"] =\n            "{data}",\n')

    # Which meaning-group each icon is in, so a picker of two thousand is a
    # picker of fifteen groups of about a hundred. Written by
    # tools/panel/groups.py; an icon it has not placed is under "ui".
    import json

    grouping = json.loads((ROOT / "tools" / "icon-groups.json").read_text(encoding="utf-8"))
    order = grouping["order"]
    placed = grouping["groups"]
    member = "".join(
        f'        ["{key}"] = "{placed.get(name, "ui")}",\n' for key, name in ICONS.items()
    )
    ids = ", ".join(f'"{g}"' for g in order)

    GENERATED.write_text(
        '// Generated by tools/fetch_icons.py. Do not edit by hand.\n'
        '// Hugeicons free set, MIT. Sources in assets/icons-src.\n'
        '\n'
        'namespace Mcd.App.Widgets;\n'
        '\n'
        '/// <summary>The icons a widget can be drawn with, as path data on a 24 by 24 grid.</summary>\n'
        'public static class IconLibrary\n'
        '{\n'
        '    /// <summary>The grid the paths are drawn on. Icons are scaled from this.</summary>\n'
        '    public const double Grid = 24;\n'
        '\n'
        '    /// <summary>Every icon, by the name stored in config.json.</summary>\n'
        '    public static IReadOnlyDictionary<string, string> Paths { get; } =\n'
        '        new Dictionary<string, string>(StringComparer.Ordinal)\n'
        '    {\n'
        + "".join(rows)
        + '    };\n'
        '\n'
        '    /// <summary>The meaning-groups icons are picked from, in the order they are listed.</summary>\n'
        f'    public static IReadOnlyList<string> GroupIds {{ get; }} = [{ids}];\n'
        '\n'
        '    /// <summary>Which group each icon is in.</summary>\n'
        '    public static IReadOnlyDictionary<string, string> Groups { get; } =\n'
        '        new Dictionary<string, string>(StringComparer.Ordinal)\n'
        '    {\n'
        + member
        + '    };\n'
        '}\n',
        encoding="utf-8",
    )

    print(f"{len(ICONS)} icons -> {GENERATED}")


if __name__ == "__main__":
    main()
